task:
  name: Build Job
  auto_cancellation: $CIRRUS_BRANCH != 'master' && $CIRRUS_TAG != ''
  container:
    image: gradle:6.5.1-jdk8
  gradle_cache:
    folder: ~/.gradle/caches
  script: gradle build
  jar_artifacts:
    path: ./build/libs/*.jar
    type: application/java-archive
  cleanup_before_cache_script: |
    rm -rf ~/.gradle/caches/$GRADLE_VERSION/ ~/.gradle/caches/transforms-1 ~/.gradle/caches/journal-1
    find ~/.gradle/caches/ -name "*.lock" -type f -delete
